# 主要配置文件
game_settings:
  difficulty: normal
  max_players: 4

resource_paths:
  images: /path/to/images
  sounds: /path/to/sounds

# 国际化配置
i18n:
  default_language: en-US
  supported_languages:
    - en-US
    - ja-JP
    - zh-CN
