# 基本配置
app:
  name: "游戏自动化套件"
  version: "1.0.0"
  language: "zh-CN"

# 性能设置
performance:
  mode: "balanced"  # balanced, performance, power-saving
  auto_optimize: false
  resource_limits:
    cpu_threshold: 80.0
    memory_threshold: 80.0
    max_threads: 100

# 游戏设置
game:
  auto_restart: true
  max_retries: 3
  timeout: 300

# 日志设置
logging:
  level: "INFO"
  file: "logs/app.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# 测试设置
testing:
  run_automated_tests: false
  test_mode: false

# UI设置
ui:
  theme: "dark"
  refresh_rate: 1000  # ms
  window_size:
    width: 1200
    height: 800
