name: game-automation-project
type: web
env: python
region: us-east-1
buildCommand: pip install -r requirements.txt
startCommand: python main.py
envVars:
  - key: PYTHONUNBUFFERED
    value: "1"
  - key: LANG
    value: "en_US.UTF-8"
  - key: TZ
    value: "UTC"