# Game Engine Settings
game_engine:
  max_errors: 5
  max_recovery_attempts: 3
  default_run_mode: 'balanced'
  high_cpu_threshold: 90
  high_memory_threshold: 80

# AI Settings
ai_settings:
  state_size: 100
  action_size: 10
  learning_rate: 0.001
  discount_factor: 0.99
  epsilon: 0.1
  epsilon_decay: 0.995
  min_epsilon: 0.01
  batch_size: 32
  memory_size: 10000
  target_update: 10
  model_save_interval: 1000
  performance_evaluation_interval: 100

# Emulator Settings
emulator:
  auto_detect: true
  default_type: "adb"
  connection_timeout: 30
  retry_attempts: 3
  types:
    - name: "adb"
      priority: 1
      connection_method: "adb_connect"
    - name: "nox"
      priority: 2
      connection_method: "nox_connect"
      path: "C:/Program Files/Nox/bin/Nox.exe"
    - name: "bluestacks"
      priority: 3
      connection_method: "bluestacks_connect"
      path: "C:/Program Files/BlueStacks/bluestacks.exe"

# Scene Understanding Settings
scene_understanding:
  confidence_threshold: 0.7
  max_objects: 20

# Natural Language Processing Settings
nlp:
  model: "en_core_web_sm"
  max_tokens: 1000

# Reasoning Engine Settings
reasoning:
  max_inference_depth: 5
  confidence_threshold: 0.8

# Performance Settings
performance:
  monitoring_interval: 5
  log_interval: 100
  plot_interval: 500
  cpu_threshold: 80  # 新增
  memory_threshold: 80  # 新增

# Logging Settings
logging:
  level: "INFO"
  file: "game_automation.log"
  max_file_size: 10485760  # 10 MB
  backup_count: 5

# User Interface Settings
ui:
  theme: "light"
  language: "en-US"
  auto_update: true

# Plugin Settings
plugins:
  enabled: true
  directory: "plugins"
  auto_load: true

# Adaptive Difficulty Settings
adaptive_difficulty:
  enabled: true
  performance_window: 10
  high_performance_threshold: 0.8
  low_performance_threshold: 0.3
  difficulty_increase_rate: 1.1
  difficulty_decrease_rate: 0.9

# Visualization Settings
visualization:
  enabled: true
  plot_dpi: 300
  max_data_points: 1000

# Multi-threading Settings
multi_threading:
  enabled: true
  max_threads: 4
  task_queue_size: 100

# Internationalization Settings
i18n:
  default_language: "en-US"
  available_languages: ["en-US", "zh-CN", "ja-JP"]

# Test Generator Settings
test_generator:
  num_test_scenarios: 10
  max_actions_per_test: 50
  randomness_factor: 0.2
