# Game-Specific Settings

# Battle System Settings
battle:
  auto_battle:
    enabled: true
    strategy: balanced  # Possible values: aggressive, balanced, defensive
    combo_threshold: 3
    heal_threshold: 50  # Percentage of HP to trigger healing
  targeting:
    priority: ["boss", "elite", "normal"]
    smart_targeting: true
  skills:
    auto_skill: true
    skill_priority: [3, 1, 2]  # Skill numbers in order of priority
    energy_threshold: 80  # Minimum energy percentage to use skills

# Character Settings
character:
  auto_level_up: true
  auto_equip: true
  inventory:
    auto_sort: true
    auto_sell: false
    keep_rarity: ["legendary", "epic", "rare"]
  equipment:
    auto_enhance: true
    max_enhance_level: 20
    material_quality: ["normal", "rare"]

# Resource Management
resources:
  auto_collect: true
  collection_radius: 50  # pixels
  minimum_stamina: 20
  stamina_reserve: 10
  auto_use_items:
    enabled: true
    item_priority: ["stamina_potion", "revival_potion"]

# Rogue Mode Settings
rogue:
  enabled: true
  difficulty: normal  # Possible values: easy, normal, hard
  blessing_system:
    auto_select: true
    priority: ["damage", "defense", "utility"]
  path_selection:
    strategy: balanced  # Possible values: risky, balanced, safe
    prefer_elites: true

# Performance Settings
performance:
  frame_skip: 2
  animation_quality: high  # Possible values: low, medium, high
  effects_quality: high
  resolution: native  # Possible values: low, medium, high, native

# Auto-Navigation
navigation:
  pathfinding: true
  obstacle_avoidance: true
  map_refresh_rate: 1.0  # seconds
  stuck_detection:
    enabled: true
    timeout: 5  # seconds
    retry_attempts: 3

# Scene Recognition
scene:
  recognition_interval: 0.5  # seconds
  confidence_threshold: 0.85
  retry_on_fail: 3
  important_scenes:
    - battle_start
    - level_up
    - reward_screen
    - death_screen

# Debug Settings
debug:
  show_coordinates: false
  show_pathfinding: false
  save_screenshots: false
  log_battles: true
  performance_monitoring: true
